spring:
  application:
    name: server
  datasource:
    url: jdbc:postgresql://localhost:5432/urban_server
    username: postgres
    password: root
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      connection-timeout: 30000
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 25
        order_inserts: true
        order_updates: true
        query:
          in_clause_parameter_padding: true
        generate_statistics: false
    hibernate:
      ddl-auto: validate
    open-in-view: false
  output:
    ansi:
      enabled: ALWAYS
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    parameters:
      searchPath: classpath:db/changelog/
    database-change-log-table: database changelog
    database-change-log-lock-table: databasechangeloglock
    drop-first: false
    label-filter: postgresql
  mvc:
    servlet:
      load-on-startup: 1
  main:
    lazy-initialization: true
    banner-mode: off
  mail:
    properties:
      mail.smtp:
          auth: true
          starttls.enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    host: smtp.gmail.com
    port: 587
    username: nagarajukasarla79@gmail.com
    password: duarabbmislklnjn

logging:
  level:
    liquibase: INFO
    org.hibernate: INFO
    org.springframework: INFO